### ISSUE TITLE
Chapel compilation times out for simple programs

### ISSUE THREAD

**Issue by riftEmber** [attempt-this-online/attempt-this-online#110]
Attempting to compile a [simple Chapel program](https://ato.pxeger.com/run?1=m70sOSOxIDVnwYKlpSVpuhY7yosyS1Jz8jSUMlJzcvJ1FMrzi3JSlDStIdJQVTDVAA) times out. The Chapel compiler is relatively slow (hello world is ~10s on a modern computer), but it is my understanding that it was previously succeeding at least in the backend as of the merge of https://github.com/attempt-this-online/attempt-this-online/pull/102.

Using the Chapel compiler's `--print-passes` flag, we were able to determine that compilation is timing out during the `resolve` pass ([example](https://ato.pxeger.com/run?1=m70sOSOxIDVnU7SSrm5BUWZeiW5BYnFxarFS7IKlpSVpuhY7yosyS1Jz8jSUMlJzcvJ1FMrzi3JSlDStIdJQVQugNAA)), which is indeed the most time-consuming pass. If we [test with Chapel code that fails to even parse](https://ato.pxeger.com/run?1=m70sOSOxIDVnU7SSrm5BUWZeiW5BYnFxarFS7IKlpSVpuhZLEotT0iBMqMgCKA0A), we quickly get back an error message instead.

**Comment by bradcray** [comment]
@pxeger : We're very motivated to help with this as best we can, but are not sure how to proceed.  Please let us know if you have any ideas or steps to take to try and reproduce or dig into it deeper.

My best initial guess was that maybe we were hitting memory limits or something like that, but the "Timing Details" section didn't give any obvious red flags that there was anything to that guess.

**Comment by pxeger** [comment]
It's probably one of the languages that mysteriously gets stuck in an infinite loop. It's an extremely irritating problem but I've so far been completely unable to work out why it happens. I'm also not very motivated to work on an undiagnosable problem that probably has a really complicated solution.

**Comment by bradcray** [comment]
@pxeger: What other languages/configurations are exhibiting this infinite loop behavior?  And did you do something to diagnose the problem as being an infinite loop rather than some other cause?  (e.g., swapping or some other performance bottleneck that grinds things to a virtual halt?)

**Comment by pxeger** [comment]
Sorry, I meant infinite loop as a general term. I just assumed it was a deadlock, not poor performance of any particular category.

**Comment by bradcray** [comment]
OK, thanks.

Again, if there's something we could do to help investigate or help out here, we'd definitely be interested in doing that (in the sense that we have users who have enthusiastically requested the ability to use Chapel on ATO and we'd like to make them happy if possible).  We don't know the ATO framework well enough to have a sense of where to start, so if you had any tips on reproducing the behavior locally or digging below the surface of what's available through the website, that would definitely be of interest to us.  And if you've seen similar behavior from other languages, that could also be useful to see whether there are any obvious commonalities.

Thanks again.

**Comment by pxeger** [comment]
If you'd like to try investigating, ATO's architecture is hopefully fairly well-documented - look at [architecture.md](https://github.com/attempt-this-online/attempt-this-online/blob/main/docs/architecture.md) and [contributing.md](https://github.com/attempt-this-online/attempt-this-online/blob/main/docs/contributing.md), and feel free to ask me if you have any questions.

If you're able to, you can set up a virtual machine running Arch Linux and install ATO (see [installation.md](https://github.com/attempt-this-online/attempt-this-online/blob/main/docs/installation.md)), which could help you debug. Otherwise, start with the instructions for backend development in the contributing docs, although they're not very detailed so you might need my help.

You might want to join [the chat room](https://chat.stackexchange.com/rooms/122645/attempt-this-online) for an interactive conversation, although it'd have to be tomorrow (UK time).

(You'll need a StackExchange account with at least 20 reputation to join the chat room. If you don't, I can ask for you to be manually granted access)

**Comment by pxeger** [comment]
Actually, never mind, I just had a <s>stroke of genius</s> reasonable hunch that proved to be correct. Chapel is using more memory than the sandbox allows.

I just tried temporarily changing the sandbox memory limit to effectively unlimited, and it worked fine after a few seconds. I'll investigate more

**Comment by pxeger** [comment]
ATO uses the [cgroupv2 memory controller](https://docs.kernel.org/admin-guide/cgroup-v2.html#memory) to restrict memory usage, with these settings:
- `memory.high`: 200MiB
- `memory.max`: 256MiB

The kernel docs say

> If a cgroup’s usage goes over the high boundary, the processes of the cgroup are throttled and put under heavy reclaim pressure

So, presumably, chapel is using more than 200MiB memory, and then gets throttled massively by the scheduler, which causes it to time out.

I'll have a look at better ways to limit memory usage that give the process more of a hint that it needs to reduce memory usage (by returning ENOMEM on memory allocations, for example).

**Comment by pxeger** [comment]
TIO uses cgroup v1's memory "soft limit" feature: https://github.com/TryItOnline/tryitonline/blob/898a41f69eeeff915b579bf4602b3ed9aea07910/bin/run#L22 which seems much more like what we want for ATO:
https://docs.kernel.org/admin-guide/cgroup-v1/memory.html#soft-limits

ATO uses cgroup v2 though which doesn't seem to have any equivalent feature...

**Comment by pxeger** [comment]
It seems like Linux basically doesn't have any robust solution to limit memory usage anyway, so I might as well give up and just set the limit higher. (I've set it to 512MB).

If any languages run out of memory past that point then I won't be able to do anything about it and it will have to be up to the language developers to try and reduce memory consumption

**Comment by pxeger** [comment]
It's fixed already on staging.ato.pxeger.com, and I'll deploy the fix to production tomorrow probably

**Comment by bradcray** [comment]
Sweet!  I didn't know about the staging site, but just verified that it works, both with a simple "Hello, world!" program and one of our longer Advent of Code 2022 codes.

I've just filed a PR today that would bring our version up-to-date with our December release.  I'm not sure whether you'd want to try to roll that into this next release, or avoid changing too many things at once (I'm not sure which I'd prefer either, TBH...).

BTW, I'm really impressed with ATO so far—thanks for making it a reality!  It's got some nice improvements on TIO, my favorite of which is having the URL continually update to reflect the current contents (I can't tell you how many times I mistakenly copy-pasted the TIO URL from my browser's bar rather than clicking the buttons required to copy it to the clipboard).  That's a huge ergonomic improvement.

One feature I always wanted from TIO that I'm wondering if you've considered for ATO would be having line numbers next to the source code so that if errors are reported, it's easy to correlate them to a specific line of code.  No idea how hard this would be to implement, though.  If it's an idea you like, I'd be happy to open an issue for it.

**Comment by pxeger** [comment]
Language updates are independent of ATO releases, and I tend to be pretty arbitrary with what deserves a new release anyway. Both this fix, and the Chapel version bump, are now deployed on https://ato.pxeger.com

**Comment by bradcray** [comment]
Awesome, thanks @pxeger!  I just ran it through similar paces as the staged 1.28.0 version and things look good.  Thanks for the time spent investigating this this week!

**Comment by bradcray** [comment]
As a follow-up: I've now updated our webpages to replace or complement TIO links with ATO ones, which feels **very** good:

* https://chapel-lang.org/
* https://chapel-lang.org/learning-code.html
* http://web.us.cray.com/~bradc/chapel.cray.com/tryit.html

Next up is an edit to the StackOverflow metadata page for Chapel to refer to ATO as well.
