### ISSUE TITLE
Syntax highlighting

### ISSUE THREAD

**Issue by Oisov** [attempt-this-online/attempt-this-online#21]
I was thinking about what could make ATO more attractive to use for new users and syntax highlighting came to mind. 

## Possible outline 

- [ ] Implement a simple react code editor which can support syntax highlighting. [Something like this perhaps.](https://github.com/satya164/react-simple-code-editor)
- [ ] Add syntax a small syntax highlight library. I would recommend [Prism](https://github.com/PrismJS/prism) as it seems fairly easy to use and include new languages.
- [ ] Figure out a way to change languages on the fly. The API does not support directly fetching out their supported languages, see https://github.com/PrismJS/prism/issues/2522. However, as mentioned in the thread there are [ways to get around this](https://codesandbox.io/s/practical-cray-bruxb?file=/src/index.js) and fetching a list of supported languages. If the language is not supported, simply apply no highlighting.
- [ ] Make small changes to the CSS to match the CSS on the site. For instance there exists a [CSS generator for Prism](https://k88hudson.github.io/syntax-highlighting-theme-generator/www/).

## Issues

* *Few esolangs have support for highlighting.* Is this really ATO's fault/responsibility? As mentioned before it should be the authors of languages who ideally add languages to ATO, and similarly they could add languages to Prism as mentioned above. I myself have thought about adding Jelly to Prism, and it does not seem particularly hard. In addition most mainstream languages are supported.

**Comment by pxeger** [comment]
This is beyond the scope of what I want ATO to do at the moment, and probably ever, mainly because it creates a whole new opportunity for issues in maintaining more parts of the project that are really only tangential to its goals.

- the target users, code golfers, often push languages' syntax to their absolute limits, so there will end up being a lot of issues like "`1and` in Python is highlighted wrong!" which we will have to either send upstream to Prism/whoever to fix, or we have to contribute and maintain fixes for these as well ourselves
  - In that example in particular, that syntax is going to be deprecated in a future version of Python, but golfers will want that version of Python to be kept around - what do we do when Prism inevitably update their syntax highlighting to match this but people here are still using an old version that no longer has syntax highlighting - or syntax highlighting that's subtly and annoyingly wrong?
- > In addition most mainstream languages are supported
  - Unfortunately, only a few mainstream languages are in common use by golfers (like Python and JS, whereas Go isn't used actively at all), so this doesn't really improve the argument
- > they could add languages to Prism
  - I suspect the Prism authors aren't too interested in adding and - crucially - maintaining support for a language used only by 3 people (and I'm definitely not)
- It would also increase the barrier to entry for adding new languages (ATO was created with this among its biggest design goals). Even if it isn't required when adding one, it creates pressure to add it because users are likely to expect it
- What about languages like Unary, Malbolge, Bubblegum, assembled machine code languages, and others where it can't possibly make sense to implement syntax highlighting?

I also don't really want to complicate the editing component too much because that would also require maintainance and create more issues to support (e.g. "add vim keybindings", and then if I added that, "vim keybindings needs to support `ZZ` as well as `:wq`", etc.), which I would consider to be a solved problem - users should use their own personal editor, which they can make do exactly what they want.

Sorry, but I'm not going to work on this. Someone else is welcome to implement it on a fork, but I don't expect I'll merge the changes either.
