### ISSUE TITLE
Add Curry KiCS2

### ISSUE THREAD

**Issue by Wheatwizard** [attempt-this-online/attempt-this-online#49]
It would be nice to have a version of the Curry programming language.  In particular the KiCS2 implementation is a popular one and is not available on TIO.

Installation instructions can be found [here](https://git.ps.informatik.uni-kiel.de/curry/kics2/-/blob/master/INSTALL.md).

**Comment by pxeger** [comment]
Do you want KiCS2 v2.3.0 (seems to be more stable) or v3.0.0 (released January 2022)? I can't find the source code for the latter, and there seem to only be Debian-based builds available.

FYI, A while ago I tried to add Curry PAKCS, but got stuck because it requires `/tmp` to be writeable which isn't (yet) possible on ATO. I never got a reply to my email to pakcs@curry-lang.org asking for help overriding the temporary directory.

Now I think about it, it probably shouldn't be *too* hard to allow `/tmp` to be writeable. (It might break some other languages though).

**Comment by Wheatwizard** [comment]
There seem to be tarballs for v2.3.0 [on the KiCS2 download page](https://www-ps.informatik.uni-kiel.de/kics2/download.html).  I can't find any information on what has been changed between v2.3.0 and v3.0.0.  It seems like most the information (tutorials available documentation etc.) is and will be on v3.0.0 so I think that would be preferable.

**Comment by AlephAlpha** [comment]
The release notes for KiCS2 can be found [here](https://git.ps.informatik.uni-kiel.de/curry/kics2/-/blob/master/RELNOTES.md).

**Comment by pxeger** [comment]
I've found that PAKCS can have its tmp directory overriden with `-Dtmpdir=`

**Comment by pxeger** [comment]
I've finally got around to adding PAKCS: https://staging.ato.pxeger.com/run?1=m706ubSoqDK-IDE7uXjBgqWlJWm6FttzEzPzFGwVCkpLgkuKfPIUlDJSc3LylSCyUEUwxQA

I'm working on KiCS2 now.

**Comment by pxeger** [comment]
I added this a while ago but never closed the issue!
